<?php
/*
 * OverHAL - Convertissez vos imports éditeurs en TEI - Convert your publisher imports to TEI
 *
 * Copyright (C) 2023 Olivier Troccaz (olivier.troccaz@cnrs.fr) and Laurent Jonchère (laurent.jonchere@univ-rennes.fr)
 * Released under the terms and conditions of the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.txt)
 *
 * Equivalence du terme 'Université' pour différents pays - Equivalence of the term 'University' for different countries
 */
 
$UNIV_LISTE = array(
0 => array("pays"=>"France", "univ"=>"Université "),
1 => array("pays"=>"Italy", "univ"=>"Universita "),
2 => array("pays"=>"Democratic Republic of the Congo ", "univ"=>"Universite "),
3 => array("pays"=>"France ", "univ"=>"Université "),
4 => array("pays"=>"Madagascar ", "univ"=>"Universite "),
5 => array("pays"=>"Cameroon ", "univ"=>"Universite "),
6 => array("pays"=>"Ivory Coast ", "univ"=>"Universite "),
7 => array("pays"=>"Niger ", "univ"=>"Universite "),
8 => array("pays"=>"Burkina Faso ", "univ"=>"Universite "),
9 => array("pays"=>"Mali ", "univ"=>"Universite "),
10 => array("pays"=>"Senegal ", "univ"=>"Universite "),
11 => array("pays"=>"Chad ", "univ"=>"Universite "),
12 => array("pays"=>"Guinea ", "univ"=>"Universite "),
13 => array("pays"=>"Rwanda ", "univ"=>"Universite "),
14 => array("pays"=>"Belgium ", "univ"=>"Universite "),
15 => array("pays"=>"Burundi ", "univ"=>"Universite "),
16 => array("pays"=>"Benin ", "univ"=>"Universite "),
17 => array("pays"=>"Haiti ", "univ"=>"Universite "),
18 => array("pays"=>"Switzerland ", "univ"=>"Universite "),
19 => array("pays"=>"Togo ", "univ"=>"Universite "),
20 => array("pays"=>"Central African Republic ", "univ"=>"Universite "),
21 => array("pays"=>"Republic of the Congo ", "univ"=>"Universite "),
22 => array("pays"=>"Gabon ", "univ"=>"Universite "),
23 => array("pays"=>"Djibouti ", "univ"=>"Universite "),
24 => array("pays"=>"Equatorial Guinea ", "univ"=>"Universite "),
25 => array("pays"=>"Comoros ", "univ"=>"Universite "),
26 => array("pays"=>"Luxembourg ", "univ"=>"Universite "),
27 => array("pays"=>"Vanuatu ", "univ"=>"Universite "),
28 => array("pays"=>"Seychelles ", "univ"=>"Universite "),
29 => array("pays"=>"Monaco", "univ"=>"Universite "),
30 => array("pays"=>"Mexico", "univ"=>"Universidad "),
31 => array("pays"=>"Colombia", "univ"=>"Universidad "),
32 => array("pays"=>"Spain", "univ"=>"Universidad "),
33 => array("pays"=>"Argentina", "univ"=>"Universidad "),
34 => array("pays"=>"Peru", "univ"=>"Universidad "),
35 => array("pays"=>"Venezuela", "univ"=>"Universidad "),
36 => array("pays"=>"Chile", "univ"=>"Universidad "),
37 => array("pays"=>"Ecuador", "univ"=>"Universidad "),
38 => array("pays"=>"Guatemala", "univ"=>"Universidad "),
39 => array("pays"=>"Cuba", "univ"=>"Universidad "),
40 => array("pays"=>"Bolivia", "univ"=>"Universidad "),
41 => array("pays"=>"Dominican Republic", "univ"=>"Universidad "),
42 => array("pays"=>"Honduras", "univ"=>"Universidad "),
43 => array("pays"=>"Paraguay", "univ"=>"Universidad "),
44 => array("pays"=>"El Salvador", "univ"=>"Universidad "),
45 => array("pays"=>"Nicaragua", "univ"=>"Universidad "),
46 => array("pays"=>"Costa Rica", "univ"=>"Universidad "),
47 => array("pays"=>"Puerto Rico", "univ"=>"Universidad "),
48 => array("pays"=>"Panama", "univ"=>"Universidad "),
49 => array("pays"=>"Uruguay", "univ"=>"Universidad "),
50 => array("pays"=>"Equatorial Guinea", "univ"=>"Universidad "),
51 => array("pays"=>"Australia", "univ"=>"University "),
52 => array("pays"=>"New Zealand", "univ"=>"University "),
53 => array("pays"=>"United Kingdom", "univ"=>"University "),
54 => array("pays"=>"United States of America", "univ"=>"University "),
55 => array("pays"=>"Scotland", "univ"=>"University "),
56 => array("pays"=>"Ireland", "univ"=>"University "),
57 => array("pays"=>"Brazil ", "univ"=>"universidade "),
58 => array("pays"=>"Mozambique", "univ"=>"universidade "),
59 => array("pays"=>"Angola", "univ"=>"universidade "),
60 => array("pays"=>"Portugal", "univ"=>"universidade "),
61 => array("pays"=>"Guinea-Bissau", "univ"=>"universidade "),
62 => array("pays"=>"East Timor", "univ"=>"universidade "),
63 => array("pays"=>"Equatorial Guinea ", "univ"=>"universidade "),
64 => array("pays"=>"Macau", "univ"=>"universidade "),
65 => array("pays"=>"Cape Verde", "univ"=>"universidade "),
66 => array("pays"=>"Sao Tome", "univ"=>"universidade "),
67 => array("pays"=>"Germany", "univ"=>"Universitat "),
68 => array("pays"=>"Austria", "univ"=>"Universitat "),
69 => array("pays"=>"Switzerland", "univ"=>"Universitat "),
70 => array("pays"=>"Luxembourg", "univ"=>"Universitat "),
71 => array("pays"=>"Liechtenstein", "univ"=>"Universitat "),
72 => array("pays"=>"Netherlands", "univ"=>"Universiteit ")
);
?>