<?php
/*
 * OverHAL - Convertissez vos imports éditeurs en TEI - Convert your publisher imports to TEI
 *
 * Copyright (C) 2023 Olivier Troccaz (olivier.troccaz@cnrs.fr) and Laurent Jonchère (laurent.jonchere@univ-rennes.fr)
 * Released under the terms and conditions of the GNU General Public License (https://www.gnu.org/licenses/gpl-3.0.txt)
 *
 * Equivalences intitulés et codes unités - Equivalence of unit titles and codes
 */
 
$search = array(
"Fonctions optiques pour les technologies de l'information",
"Institut d'électronique et de télécommunications de Rennes",
"Institut de recherche en informatique et systèmes aléatoires",
"Institut de recherche mathématique de Rennes",
"Laboratoire traitement du signal et de l'image",
"Vision, Action et Gestion d'Information en Santé",
"Géosciences Rennes",
"Institut de physique de Rennes",
"Institut des sciences chimiques de Rennes",
"Laboratoire de génie civil et génie mécanique",
"Observatoire des Sciences de l'Univers de Rennes",
"ARN régulateurs bactériens et médecine",
"Biosit",
"Structure Fédérative de Recherche en Biologie Santé",
"Centre d'investigation clinique de Rennes",
"Chemistry, Oncogenesis, Stress and Signaling",
"Comportement et noyaux gris centraux",
"Behaviors and Basal Ganglia",
"Écosystèmes, biodiversité, évolution",
"Éthologie animale et humaine",
"Géoarchitecture : Territoires, Urbanisation, Biodiversité, Environnement",
"Institut de génétique et développement de Rennes",
"Institut de génétique, environnement et protection des plantes",
"Institut de recherche en santé, environnement et travail",
"Microenvironment, Cell Differentiation, Immunology and Cancer",
"Nutrition, Métabolismes et Cancer",
"Recherche en Pharmaco-épidémiologie et Recours aux Soins",
"Centre de recherches sur l'action politique en Europe",
"Centre Atlantique de Philosophie",
"Centre de droit des affaires",
"Centre de recherche en archéologie, archéosciences, histoire",
"Centre de recherche en économie et management",
"Institut de l'Ouest : droit et Europe",
"Institut du droit public et de la science politique",
"Laboratoire mouvement, sport et santé",
"Foie métabolisme et cancer",
"Microenvironnement et Cancer",
"Fonction, structure et inactivation d'ARN bactériens",
"Optical Functions for Information and Communication Technologies",
"Institute of Electronics and Telecommunications of Rennes",
"Institute for Research in Computer Science and Random Systems",
"Mathematics Research Institute of Rennes",
"Vision, Action and Information Management System in Health",
"Geosciences Rennes",
"Rennes Institute of Physics",
"Chemical Institute of Rennes",
"Bacterial regulatory RNAs and Medicine",
"Biology Health Innovation and Technology",
"Clinical Investigation Center",
"Chemistry, Oncogenesis, Stress and Signaling",
"Ecosystems, Biodiversity, Evolution",
"Animal and Human Ethology",
"Institute of Genetics and Development of Rennes",
"Institute of Genetics, Environment and Plant Protection",
"Research Institute in Health, Environment and Occupation",
"Microenvironment, Cell Differentiation, Immunology and Cancer",
"Nutrition, Metabolisms and Cancer",
"Research in Pharmacoepidemiology and Access to Care",
"Political Action in Europe",
"Archaeology, Archaeoscience and History",
"Center for Research in Economics and Management",
"Western Institute of Law and European Studies",
"Public Law and Political Science Institute",
"Movement, Sport and Health Sciences",
"M2S Laboratory",
"Behavior and Basal Ganglia"
);

$replace = array(
"UMR6082",
"UMR6164",
"UMR6074",
"UMR6625",
"U1099",
"U1228",
"UMR6118",
"UMR6251",
"UMR6226",
"EA3913",
"UMS3343",
"U1230",
"Biosit",
"Biosit",
"CIC 1414",
"U1242",
"EA4712",
"EA4712",
"UMR6553",
"UMR6552",
"EA7462",
"UMR6290",
"IGEPP",
"U1085",
"U1236",
"U1241",
"EA7449",
"UMR6051",
"EA7463",
"EA3195",
"UMR6566",
"UMR6211",
"UMR6262",
"EA4640",
"EA1274",
"U991",
"U917",
"U835",
"UMR6082",
"UMR6164",
"UMR6074",
"UMR6625",
"U1228",
"UMR6118", 
"UMR6251",
"UMR6226",
"U1230",
"Biosit",
"CIC",
"U1242",
"UMR6553",
"UMR6552",
"UMR6290",
"UMR1349",
"U1085",
"U1236",
"U1241",
"EA7449",
"UMR6051",
"UMR6566",
"UMR6211",
"UMR6262",
"EA4640",
"EA1274",
"EA1274",
"EA 4712"
);
?>